name: gaza_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_screenutil:
  device_preview:
  flutter_svg:
  google_language_fonts:
  cached_network_image:
  firebase_core:
  firebase_storage:
  cloud_firestore:
  image_picker:
  logger: ^1.1.0
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

